// Generated by CoffeeScript 1.3.3

/*
Sofoque (/sɔːˈfɔː.kɛ/) a profiler middleware tospot performance suffocating conditions in express/connect applications
*/


(function() {
  var CPU_SAMPLE_RATE, UnsupportedPlatform, conf, currentCPULoad, defaultCallback, fs, getCPUload, os, sofoqueMiddleware,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  os = require('os');

  fs = require('fs');

  if (['linux', 'solaris'].indexOf(os.platform()) === -1) {
    UnsupportedPlatform = (function(_super) {

      __extends(UnsupportedPlatform, _super);

      function UnsupportedPlatform() {
        return UnsupportedPlatform.__super__.constructor.apply(this, arguments);
      }

      return UnsupportedPlatform;

    })(Error);
    throw new UnsupportedPlatform("Only 'linux' and 'solaris' platforms are supported, but you are running '" + (os.platform()) + "'.");
  }

  conf = {};

  defaultCallback = console.error;

  CPU_SAMPLE_RATE = 250;

  currentCPULoad = 0;

  (getCPUload = function() {
    var getProcInfo, start;
    getProcInfo = function(callback) {
      return fs.readFile("/proc/" + process.pid + "/stat", function(err, data) {
        return callback(data.toString().split(' ').splice(13, 2).reduce((function(a, b) {
          return Number(b) + a;
        }), 0));
      });
    };
    start = 0;
    return getProcInfo(function(data) {
      start = {
        time: Date.now(),
        data: data
      };
      return setTimeout(function() {
        return getProcInfo(function(data) {
          var time;
          time = Date.now() - start.time;
          currentCPULoad = Math.round((data - start.data) * (1000 / time) * 100) / 100;
          return getCPUload();
        });
      }, CPU_SAMPLE_RATE);
    });
  })();

  sofoqueMiddleware = function(req, res, next) {
    if (req.sofoque != null) {
      next();
    }
    req.sofoque = true;
    res.on('header', function() {
      res.sofoque.query = req.query;
      res.sofoque.body = req.body;
      res.sofoque.after = {
        cpuLoad: {
          system: os.loadavg,
          process: currentCPULoad
        },
        memoryUsage: process.memoryUsage()
      };
      return conf.callback({
        Sofoque: res.sofoque
      });
    });
    res.sofoque = {
      method: req.method,
      path: req.path,
      duration: Date.now(),
      before: {
        cpuLoad: {
          system: os.loadavg,
          process: currentCPULoad
        },
        memoryUsage: process.memoryUsage()
      }
    };
    return next();
  };

  module.exports = {
    getCPUload: function() {
      return currentCPULoad;
    },
    middleware: function(callback) {
      if (callback == null) {
        callback = defaultCallback;
      }
      conf = {
        callback: callback
      };
      return sofoqueMiddleware;
    }
  };

}).call(this);
